openapi: 3.0.1
info:
  title: SOG Seller API
  description: testing this stuff
  contact:
    email: mpannella@sourceofgoods.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Source-Of-Goods/sog/1.0.0
tags:
- name: sellers
  description: Secured Seller-only calls
paths:
  /products:
    get:
      tags:
      - sellers
      summary: Get products
      description: |
        Retrieve list of all products, or just one by sku
      operationId: productsGet
      parameters:
      - name: sku
        in: query
        description: item sku
        schema:
          type: string
      - name: limit
        in: query
        description: limit number of results
        schema:
          type: integer
      - name: offset
        in: query
        description: offset from 0
        schema:
          type: integer
      responses:
        200:
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                properties:
                  offset:
                    type: integer
                    description: the offset id to be used in future calls, for pagination
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        400:
          description: bad input parameter
          content: {}
  /orders:
    get:
      tags:
      - sellers
      summary: Get orders
      description: |
        Get a list of orders
      operationId: ordersGet
      parameters:
      - name: order_num
        in: query
        description: order number
        schema:
          type: string
      - name: status
        in: query
        description: status of order
        schema:
          type: string
      - name: channel
        in: query
        description: order channel
        schema:
          type: string
      - name: from_date
        in: query
        description: starting datetime ISO-8601
        schema:
          type: string
          format: date-time
      - name: to_date
        in: query
        description: ending datetime ISO-8601
        schema:
          type: string
          format: date-time
      - name: limit
        in: query
        description: limit number of results
        schema:
          type: integer
      - name: offset
        in: query
        description: offset from 0
        schema:
          type: integer
      responses:
        200:
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        400:
          description: bad input parameter
          content: {}
    post:
      tags:
      - sellers
      summary: creates new order
      description: Add a new order into the system
      operationId: orderPost
      requestBody:
        description: Order information and items
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: false
      responses:
        201:
          description: order created
          content: {}
        400:
          description: invalid input, object invalid
          content: {}
      x-codegen-request-body-name: orderInfo
components:
  schemas:
    Product:
      type: object
      properties:
        sku:
          type: string
        name:
          type: string
        mpn:
          type: string
        upc:
          type: string
        asin:
          type: string
        description:
          type: string
        leadTime:
          type: integer
        leadTimeBusDays:
          type: integer
        size:
          type: string
        color:
          type: string
        cost:
          type: number
          format: float
        ship48:
          type: number
          format: float
        mapPrice:
          type: number
          format: float
        quantityAvailable:
          type: integer
        weight:
          type: number
          description: in lbs
          format: float
        shipWeight:
          type: number
          description: in lbs
          format: float
    OrderItem:
      required:
      - quantity
      - sku
      type: object
      properties:
        sku:
          type: string
        quantity:
          type: integer
        price:
          type: number
          format: float
        shipping_price:
          type: number
          format: float
    Order:
      required:
      - channel
      - channel_order_id
      - email
      - order_items
      - phone
      - ship_address_1
      - ship_by_date
      - ship_city
      - ship_country
      - ship_state
      - ship_zip
      type: object
      properties:
        channel:
          type: string
          enum:
          - Amazon
          - Ebay
          - Custom Resource
        channel_order_id:
          type: string
        order_date:
          type: string
          format: date
        ship_by_date:
          type: string
          format: date
        ship_name:
          type: string
        ship_address_1:
          type: string
        ship_address_2:
          type: string
        ship_city:
          type: string
        ship_state:
          type: string
        ship_zip:
          maxLength: 7
          minLength: 7
          type: string
        ship_country:
          type: string
        bill_name:
          type: string
        bill_address_1:
          type: string
        bill_address_2:
          type: string
        bill_city:
          type: string
        bill_zip:
          maxLength: 7
          minLength: 7
          type: string
        bill_country:
          type: string
        phone:
          type: string
        email:
          type: string
        order_items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
      description: an order
